### ISSUE TITLE
como se implementa en Android?

### ISSUE THREAD

**Issue by Yerman3000** [H4ad/cordova-whatsapp-sticker-plugin#1]
hay forma de implementarlo en android al plugin? (cordova-whatsapp-sticker-plugin)

**Comment by H4ad** [comment]
Sobre o plugin no Android, não será a implementação dele em si. Você criará arquivos diretamente na sua pasta `Platforms/Android`, e utilizando um outro plugin chamado `Web Intents` eu chamava o código nativo. 

Eu estou sem tempo agora, mas assim que der, eu posto um passo a passo de que arquivos adicionar, e como implementar na versão em Android.

**Comment by H4ad** [comment]
Estou fechando essa issue, a documentação foi adicionada, veja [aqui.](https://github.com/H4ad/cordova-whatsapp-sticker-plugin/blob/master/Android.md)
